### ISSUE TITLE
Request Compatibility with JDK 11

### ISSUE THREAD

**Issue by NovaPixell** [Codeland473/uhc-plugin#6]
Hi! Please build this plugin with JDK 11.

**Comment by NovaPixell** [comment]
I need it for a big large server network, please

**Comment by balduvian** [comment]
https://github.com/Codeland473/uhc-plugin/commit/3ce2ee482b8623e4ab3838c5bab43cb9dd1982f0
latest commit on master changes the jvmTarget for compileKotlin to JVM 11
